### ISSUE TITLE
Two way binding

### ISSUE THREAD

**Issue by geiszla** [geaz/sharpWebview#2]
Hi, first I just wanna say, I love this project and started to seriously look into it.

I've already made binding work from JS to .Net (so I can call .Net logic from JS), but I haven't really found in the Readme or in examples how to do the opposite. How would one go about calling a JS function from .Net code? Is that what the `Dispatch` method is for? Or is there a way to bind functions the other way around?

Thank for your help and keep up the good work :)

**Comment by geaz** [comment]
Hi!

I think the `Evaluate` method is what you are after. With it you are able to execute any javascript code you want.

The `Dispatch` method is there for executing C# code in the webview thread.

I hope this helps :)

**Comment by geiszla** [comment]
Oh right, I missed that one, thanks 👍
